// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: atomspace.proto

package org.opencog.atomspace;

public final class AtomSpaceProtos {
  private AtomSpaceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AtomRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .atomspace.AtomRequest.AtomRequestKind kind = 1;
    /**
     * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
     */
    boolean hasKind();
    /**
     * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
     */
    org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind getKind();

    // optional fixed64 uuid = 2;
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    long getUuid();

    // optional string atom_type = 3;
    /**
     * <code>optional string atom_type = 3;</code>
     */
    boolean hasAtomType();
    /**
     * <code>optional string atom_type = 3;</code>
     */
    java.lang.String getAtomType();
    /**
     * <code>optional string atom_type = 3;</code>
     */
    com.google.protobuf.ByteString
        getAtomTypeBytes();

    // optional string node_name = 4;
    /**
     * <code>optional string node_name = 4;</code>
     */
    boolean hasNodeName();
    /**
     * <code>optional string node_name = 4;</code>
     */
    java.lang.String getNodeName();
    /**
     * <code>optional string node_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNodeNameBytes();

    // repeated fixed64 handle_seq = 5;
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    java.util.List<java.lang.Long> getHandleSeqList();
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    int getHandleSeqCount();
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    long getHandleSeq(int index);
  }
  /**
   * Protobuf type {@code atomspace.AtomRequest}
   */
  public static final class AtomRequest extends
      com.google.protobuf.GeneratedMessage
      implements AtomRequestOrBuilder {
    // Use AtomRequest.newBuilder() to construct.
    private AtomRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AtomRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AtomRequest defaultInstance;
    public static AtomRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AtomRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AtomRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind value = org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                kind_ = value;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              uuid_ = input.readFixed64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              atomType_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              nodeName_ = input.readBytes();
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                handleSeq_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              handleSeq_.add(input.readFixed64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                handleSeq_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                handleSeq_.add(input.readFixed64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          handleSeq_ = java.util.Collections.unmodifiableList(handleSeq_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencog.atomspace.AtomSpaceProtos.AtomRequest.class, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AtomRequest> PARSER =
        new com.google.protobuf.AbstractParser<AtomRequest>() {
      public AtomRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AtomRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AtomRequest> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code atomspace.AtomRequest.AtomRequestKind}
     */
    public enum AtomRequestKind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UUID = 0;</code>
       *
       * <pre>
       * get atom by handle UUID
       * </pre>
       */
      UUID(0, 0),
      /**
       * <code>NODE = 1;</code>
       *
       * <pre>
       * get node by atom_type and node_name
       * </pre>
       */
      NODE(1, 1),
      /**
       * <code>LINK = 2;</code>
       *
       * <pre>
       * get link by atom_type and handle_seq
       * </pre>
       */
      LINK(2, 2),
      ;

      /**
       * <code>UUID = 0;</code>
       *
       * <pre>
       * get atom by handle UUID
       * </pre>
       */
      public static final int UUID_VALUE = 0;
      /**
       * <code>NODE = 1;</code>
       *
       * <pre>
       * get node by atom_type and node_name
       * </pre>
       */
      public static final int NODE_VALUE = 1;
      /**
       * <code>LINK = 2;</code>
       *
       * <pre>
       * get link by atom_type and handle_seq
       * </pre>
       */
      public static final int LINK_VALUE = 2;


      public final int getNumber() { return value; }

      public static AtomRequestKind valueOf(int value) {
        switch (value) {
          case 0: return UUID;
          case 1: return NODE;
          case 2: return LINK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<AtomRequestKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<AtomRequestKind>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<AtomRequestKind>() {
              public AtomRequestKind findValueByNumber(int number) {
                return AtomRequestKind.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.opencog.atomspace.AtomSpaceProtos.AtomRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final AtomRequestKind[] VALUES = values();

      public static AtomRequestKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private AtomRequestKind(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:atomspace.AtomRequest.AtomRequestKind)
    }

    private int bitField0_;
    // required .atomspace.AtomRequest.AtomRequestKind kind = 1;
    public static final int KIND_FIELD_NUMBER = 1;
    private org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind kind_;
    /**
     * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
     */
    public org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind getKind() {
      return kind_;
    }

    // optional fixed64 uuid = 2;
    public static final int UUID_FIELD_NUMBER = 2;
    private long uuid_;
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    public long getUuid() {
      return uuid_;
    }

    // optional string atom_type = 3;
    public static final int ATOM_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object atomType_;
    /**
     * <code>optional string atom_type = 3;</code>
     */
    public boolean hasAtomType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string atom_type = 3;</code>
     */
    public java.lang.String getAtomType() {
      java.lang.Object ref = atomType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          atomType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string atom_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAtomTypeBytes() {
      java.lang.Object ref = atomType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        atomType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string node_name = 4;
    public static final int NODE_NAME_FIELD_NUMBER = 4;
    private java.lang.Object nodeName_;
    /**
     * <code>optional string node_name = 4;</code>
     */
    public boolean hasNodeName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string node_name = 4;</code>
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string node_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated fixed64 handle_seq = 5;
    public static final int HANDLE_SEQ_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> handleSeq_;
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getHandleSeqList() {
      return handleSeq_;
    }
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    public int getHandleSeqCount() {
      return handleSeq_.size();
    }
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    public long getHandleSeq(int index) {
      return handleSeq_.get(index);
    }

    private void initFields() {
      kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind.UUID;
      uuid_ = 0L;
      atomType_ = "";
      nodeName_ = "";
      handleSeq_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, kind_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAtomTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNodeNameBytes());
      }
      for (int i = 0; i < handleSeq_.size(); i++) {
        output.writeFixed64(5, handleSeq_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, kind_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAtomTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNodeNameBytes());
      }
      {
        int dataSize = 0;
        dataSize = 8 * getHandleSeqList().size();
        size += dataSize;
        size += 1 * getHandleSeqList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opencog.atomspace.AtomSpaceProtos.AtomRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code atomspace.AtomRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencog.atomspace.AtomSpaceProtos.AtomRequest.class, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder.class);
      }

      // Construct using org.opencog.atomspace.AtomSpaceProtos.AtomRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind.UUID;
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        atomType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nodeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        handleSeq_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomRequest_descriptor;
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest getDefaultInstanceForType() {
        return org.opencog.atomspace.AtomSpaceProtos.AtomRequest.getDefaultInstance();
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest build() {
        org.opencog.atomspace.AtomSpaceProtos.AtomRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest buildPartial() {
        org.opencog.atomspace.AtomSpaceProtos.AtomRequest result = new org.opencog.atomspace.AtomSpaceProtos.AtomRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.atomType_ = atomType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nodeName_ = nodeName_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          handleSeq_ = java.util.Collections.unmodifiableList(handleSeq_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.handleSeq_ = handleSeq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencog.atomspace.AtomSpaceProtos.AtomRequest) {
          return mergeFrom((org.opencog.atomspace.AtomSpaceProtos.AtomRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencog.atomspace.AtomSpaceProtos.AtomRequest other) {
        if (other == org.opencog.atomspace.AtomSpaceProtos.AtomRequest.getDefaultInstance()) return this;
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasAtomType()) {
          bitField0_ |= 0x00000004;
          atomType_ = other.atomType_;
          onChanged();
        }
        if (other.hasNodeName()) {
          bitField0_ |= 0x00000008;
          nodeName_ = other.nodeName_;
          onChanged();
        }
        if (!other.handleSeq_.isEmpty()) {
          if (handleSeq_.isEmpty()) {
            handleSeq_ = other.handleSeq_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureHandleSeqIsMutable();
            handleSeq_.addAll(other.handleSeq_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKind()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencog.atomspace.AtomSpaceProtos.AtomRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencog.atomspace.AtomSpaceProtos.AtomRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .atomspace.AtomRequest.AtomRequestKind kind = 1;
      private org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind.UUID;
      /**
       * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind getKind() {
        return kind_;
      }
      /**
       * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
       */
      public Builder setKind(org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .atomspace.AtomRequest.AtomRequestKind kind = 1;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000001);
        kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomRequest.AtomRequestKind.UUID;
        onChanged();
        return this;
      }

      // optional fixed64 uuid = 2;
      private long uuid_ ;
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public long getUuid() {
        return uuid_;
      }
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public Builder setUuid(long value) {
        bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = 0L;
        onChanged();
        return this;
      }

      // optional string atom_type = 3;
      private java.lang.Object atomType_ = "";
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public boolean hasAtomType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public java.lang.String getAtomType() {
        java.lang.Object ref = atomType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          atomType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAtomTypeBytes() {
        java.lang.Object ref = atomType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          atomType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public Builder setAtomType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        atomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public Builder clearAtomType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        atomType_ = getDefaultInstance().getAtomType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public Builder setAtomTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        atomType_ = value;
        onChanged();
        return this;
      }

      // optional string node_name = 4;
      private java.lang.Object nodeName_ = "";
      /**
       * <code>optional string node_name = 4;</code>
       */
      public boolean hasNodeName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public java.lang.String getNodeName() {
        java.lang.Object ref = nodeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nodeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNodeNameBytes() {
        java.lang.Object ref = nodeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public Builder setNodeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nodeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public Builder clearNodeName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nodeName_ = getDefaultInstance().getNodeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public Builder setNodeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nodeName_ = value;
        onChanged();
        return this;
      }

      // repeated fixed64 handle_seq = 5;
      private java.util.List<java.lang.Long> handleSeq_ = java.util.Collections.emptyList();
      private void ensureHandleSeqIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          handleSeq_ = new java.util.ArrayList<java.lang.Long>(handleSeq_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getHandleSeqList() {
        return java.util.Collections.unmodifiableList(handleSeq_);
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public int getHandleSeqCount() {
        return handleSeq_.size();
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public long getHandleSeq(int index) {
        return handleSeq_.get(index);
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder setHandleSeq(
          int index, long value) {
        ensureHandleSeqIsMutable();
        handleSeq_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder addHandleSeq(long value) {
        ensureHandleSeqIsMutable();
        handleSeq_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder addAllHandleSeq(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureHandleSeqIsMutable();
        super.addAll(values, handleSeq_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder clearHandleSeq() {
        handleSeq_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:atomspace.AtomRequest)
    }

    static {
      defaultInstance = new AtomRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:atomspace.AtomRequest)
  }

  public interface AtomsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .atomspace.AtomRequest requests = 1;
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    java.util.List<org.opencog.atomspace.AtomSpaceProtos.AtomRequest> 
        getRequestsList();
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    org.opencog.atomspace.AtomSpaceProtos.AtomRequest getRequests(int index);
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    int getRequestsCount();
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    java.util.List<? extends org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder> 
        getRequestsOrBuilderList();
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder getRequestsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code atomspace.AtomsRequest}
   */
  public static final class AtomsRequest extends
      com.google.protobuf.GeneratedMessage
      implements AtomsRequestOrBuilder {
    // Use AtomsRequest.newBuilder() to construct.
    private AtomsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AtomsRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AtomsRequest defaultInstance;
    public static AtomsRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AtomsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AtomsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                requests_ = new java.util.ArrayList<org.opencog.atomspace.AtomSpaceProtos.AtomRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              requests_.add(input.readMessage(org.opencog.atomspace.AtomSpaceProtos.AtomRequest.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          requests_ = java.util.Collections.unmodifiableList(requests_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.class, org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AtomsRequest> PARSER =
        new com.google.protobuf.AbstractParser<AtomsRequest>() {
      public AtomsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AtomsRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AtomsRequest> getParserForType() {
      return PARSER;
    }

    // repeated .atomspace.AtomRequest requests = 1;
    public static final int REQUESTS_FIELD_NUMBER = 1;
    private java.util.List<org.opencog.atomspace.AtomSpaceProtos.AtomRequest> requests_;
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    public java.util.List<org.opencog.atomspace.AtomSpaceProtos.AtomRequest> getRequestsList() {
      return requests_;
    }
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    public java.util.List<? extends org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder> 
        getRequestsOrBuilderList() {
      return requests_;
    }
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    public int getRequestsCount() {
      return requests_.size();
    }
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    public org.opencog.atomspace.AtomSpaceProtos.AtomRequest getRequests(int index) {
      return requests_.get(index);
    }
    /**
     * <code>repeated .atomspace.AtomRequest requests = 1;</code>
     */
    public org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder getRequestsOrBuilder(
        int index) {
      return requests_.get(index);
    }

    private void initFields() {
      requests_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getRequestsCount(); i++) {
        if (!getRequests(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < requests_.size(); i++) {
        output.writeMessage(1, requests_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < requests_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, requests_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opencog.atomspace.AtomSpaceProtos.AtomsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code atomspace.AtomsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.opencog.atomspace.AtomSpaceProtos.AtomsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.class, org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.Builder.class);
      }

      // Construct using org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestsBuilder_ == null) {
          requests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          requestsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomsRequest_descriptor;
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomsRequest getDefaultInstanceForType() {
        return org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.getDefaultInstance();
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomsRequest build() {
        org.opencog.atomspace.AtomSpaceProtos.AtomsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomsRequest buildPartial() {
        org.opencog.atomspace.AtomSpaceProtos.AtomsRequest result = new org.opencog.atomspace.AtomSpaceProtos.AtomsRequest(this);
        int from_bitField0_ = bitField0_;
        if (requestsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            requests_ = java.util.Collections.unmodifiableList(requests_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.requests_ = requests_;
        } else {
          result.requests_ = requestsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencog.atomspace.AtomSpaceProtos.AtomsRequest) {
          return mergeFrom((org.opencog.atomspace.AtomSpaceProtos.AtomsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencog.atomspace.AtomSpaceProtos.AtomsRequest other) {
        if (other == org.opencog.atomspace.AtomSpaceProtos.AtomsRequest.getDefaultInstance()) return this;
        if (requestsBuilder_ == null) {
          if (!other.requests_.isEmpty()) {
            if (requests_.isEmpty()) {
              requests_ = other.requests_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRequestsIsMutable();
              requests_.addAll(other.requests_);
            }
            onChanged();
          }
        } else {
          if (!other.requests_.isEmpty()) {
            if (requestsBuilder_.isEmpty()) {
              requestsBuilder_.dispose();
              requestsBuilder_ = null;
              requests_ = other.requests_;
              bitField0_ = (bitField0_ & ~0x00000001);
              requestsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRequestsFieldBuilder() : null;
            } else {
              requestsBuilder_.addAllMessages(other.requests_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRequestsCount(); i++) {
          if (!getRequests(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencog.atomspace.AtomSpaceProtos.AtomsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencog.atomspace.AtomSpaceProtos.AtomsRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .atomspace.AtomRequest requests = 1;
      private java.util.List<org.opencog.atomspace.AtomSpaceProtos.AtomRequest> requests_ =
        java.util.Collections.emptyList();
      private void ensureRequestsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          requests_ = new java.util.ArrayList<org.opencog.atomspace.AtomSpaceProtos.AtomRequest>(requests_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.opencog.atomspace.AtomSpaceProtos.AtomRequest, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder, org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder> requestsBuilder_;

      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public java.util.List<org.opencog.atomspace.AtomSpaceProtos.AtomRequest> getRequestsList() {
        if (requestsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(requests_);
        } else {
          return requestsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public int getRequestsCount() {
        if (requestsBuilder_ == null) {
          return requests_.size();
        } else {
          return requestsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest getRequests(int index) {
        if (requestsBuilder_ == null) {
          return requests_.get(index);
        } else {
          return requestsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder setRequests(
          int index, org.opencog.atomspace.AtomSpaceProtos.AtomRequest value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.set(index, value);
          onChanged();
        } else {
          requestsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder setRequests(
          int index, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.set(index, builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder addRequests(org.opencog.atomspace.AtomSpaceProtos.AtomRequest value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.add(value);
          onChanged();
        } else {
          requestsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder addRequests(
          int index, org.opencog.atomspace.AtomSpaceProtos.AtomRequest value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.add(index, value);
          onChanged();
        } else {
          requestsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder addRequests(
          org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.add(builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder addRequests(
          int index, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.add(index, builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder addAllRequests(
          java.lang.Iterable<? extends org.opencog.atomspace.AtomSpaceProtos.AtomRequest> values) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          super.addAll(values, requests_);
          onChanged();
        } else {
          requestsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder clearRequests() {
        if (requestsBuilder_ == null) {
          requests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          requestsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public Builder removeRequests(int index) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.remove(index);
          onChanged();
        } else {
          requestsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder getRequestsBuilder(
          int index) {
        return getRequestsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder getRequestsOrBuilder(
          int index) {
        if (requestsBuilder_ == null) {
          return requests_.get(index);  } else {
          return requestsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public java.util.List<? extends org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder> 
           getRequestsOrBuilderList() {
        if (requestsBuilder_ != null) {
          return requestsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(requests_);
        }
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder addRequestsBuilder() {
        return getRequestsFieldBuilder().addBuilder(
            org.opencog.atomspace.AtomSpaceProtos.AtomRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder addRequestsBuilder(
          int index) {
        return getRequestsFieldBuilder().addBuilder(
            index, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .atomspace.AtomRequest requests = 1;</code>
       */
      public java.util.List<org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder> 
           getRequestsBuilderList() {
        return getRequestsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.opencog.atomspace.AtomSpaceProtos.AtomRequest, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder, org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder> 
          getRequestsFieldBuilder() {
        if (requestsBuilder_ == null) {
          requestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.opencog.atomspace.AtomSpaceProtos.AtomRequest, org.opencog.atomspace.AtomSpaceProtos.AtomRequest.Builder, org.opencog.atomspace.AtomSpaceProtos.AtomRequestOrBuilder>(
                  requests_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          requests_ = null;
        }
        return requestsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:atomspace.AtomsRequest)
    }

    static {
      defaultInstance = new AtomsRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:atomspace.AtomsRequest)
  }

  public interface AtomResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .atomspace.AtomResult.ResultKind kind = 1;
    /**
     * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
     */
    boolean hasKind();
    /**
     * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
     */
    org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind getKind();

    // optional fixed64 uuid = 2;
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    long getUuid();

    // optional string atom_type = 3;
    /**
     * <code>optional string atom_type = 3;</code>
     */
    boolean hasAtomType();
    /**
     * <code>optional string atom_type = 3;</code>
     */
    java.lang.String getAtomType();
    /**
     * <code>optional string atom_type = 3;</code>
     */
    com.google.protobuf.ByteString
        getAtomTypeBytes();

    // optional string node_name = 4;
    /**
     * <code>optional string node_name = 4;</code>
     */
    boolean hasNodeName();
    /**
     * <code>optional string node_name = 4;</code>
     */
    java.lang.String getNodeName();
    /**
     * <code>optional string node_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNodeNameBytes();

    // repeated fixed64 handle_seq = 5;
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    java.util.List<java.lang.Long> getHandleSeqList();
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    int getHandleSeqCount();
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    long getHandleSeq(int index);
  }
  /**
   * Protobuf type {@code atomspace.AtomResult}
   */
  public static final class AtomResult extends
      com.google.protobuf.GeneratedMessage
      implements AtomResultOrBuilder {
    // Use AtomResult.newBuilder() to construct.
    private AtomResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AtomResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AtomResult defaultInstance;
    public static AtomResult getDefaultInstance() {
      return defaultInstance;
    }

    public AtomResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AtomResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind value = org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                kind_ = value;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              uuid_ = input.readFixed64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              atomType_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              nodeName_ = input.readBytes();
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                handleSeq_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              handleSeq_.add(input.readFixed64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                handleSeq_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                handleSeq_.add(input.readFixed64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          handleSeq_ = java.util.Collections.unmodifiableList(handleSeq_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencog.atomspace.AtomSpaceProtos.AtomResult.class, org.opencog.atomspace.AtomSpaceProtos.AtomResult.Builder.class);
    }

    public static com.google.protobuf.Parser<AtomResult> PARSER =
        new com.google.protobuf.AbstractParser<AtomResult>() {
      public AtomResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AtomResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AtomResult> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code atomspace.AtomResult.ResultKind}
     */
    public enum ResultKind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOT_FOUND = 0;</code>
       *
       * <pre>
       * not found
       * </pre>
       */
      NOT_FOUND(0, 0),
      /**
       * <code>NODE = 1;</code>
       *
       * <pre>
       * found a node
       * </pre>
       */
      NODE(1, 1),
      /**
       * <code>LINK = 2;</code>
       *
       * <pre>
       * found a link
       * </pre>
       */
      LINK(2, 2),
      ;

      /**
       * <code>NOT_FOUND = 0;</code>
       *
       * <pre>
       * not found
       * </pre>
       */
      public static final int NOT_FOUND_VALUE = 0;
      /**
       * <code>NODE = 1;</code>
       *
       * <pre>
       * found a node
       * </pre>
       */
      public static final int NODE_VALUE = 1;
      /**
       * <code>LINK = 2;</code>
       *
       * <pre>
       * found a link
       * </pre>
       */
      public static final int LINK_VALUE = 2;


      public final int getNumber() { return value; }

      public static ResultKind valueOf(int value) {
        switch (value) {
          case 0: return NOT_FOUND;
          case 1: return NODE;
          case 2: return LINK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultKind>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultKind>() {
              public ResultKind findValueByNumber(int number) {
                return ResultKind.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.opencog.atomspace.AtomSpaceProtos.AtomResult.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultKind[] VALUES = values();

      public static ResultKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultKind(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:atomspace.AtomResult.ResultKind)
    }

    private int bitField0_;
    // required .atomspace.AtomResult.ResultKind kind = 1;
    public static final int KIND_FIELD_NUMBER = 1;
    private org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind kind_;
    /**
     * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
     */
    public org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind getKind() {
      return kind_;
    }

    // optional fixed64 uuid = 2;
    public static final int UUID_FIELD_NUMBER = 2;
    private long uuid_;
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional fixed64 uuid = 2;</code>
     */
    public long getUuid() {
      return uuid_;
    }

    // optional string atom_type = 3;
    public static final int ATOM_TYPE_FIELD_NUMBER = 3;
    private java.lang.Object atomType_;
    /**
     * <code>optional string atom_type = 3;</code>
     */
    public boolean hasAtomType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string atom_type = 3;</code>
     */
    public java.lang.String getAtomType() {
      java.lang.Object ref = atomType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          atomType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string atom_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAtomTypeBytes() {
      java.lang.Object ref = atomType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        atomType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string node_name = 4;
    public static final int NODE_NAME_FIELD_NUMBER = 4;
    private java.lang.Object nodeName_;
    /**
     * <code>optional string node_name = 4;</code>
     */
    public boolean hasNodeName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string node_name = 4;</code>
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string node_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated fixed64 handle_seq = 5;
    public static final int HANDLE_SEQ_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> handleSeq_;
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getHandleSeqList() {
      return handleSeq_;
    }
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    public int getHandleSeqCount() {
      return handleSeq_.size();
    }
    /**
     * <code>repeated fixed64 handle_seq = 5;</code>
     */
    public long getHandleSeq(int index) {
      return handleSeq_.get(index);
    }

    private void initFields() {
      kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind.NOT_FOUND;
      uuid_ = 0L;
      atomType_ = "";
      nodeName_ = "";
      handleSeq_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, kind_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed64(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAtomTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNodeNameBytes());
      }
      for (int i = 0; i < handleSeq_.size(); i++) {
        output.writeFixed64(5, handleSeq_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, kind_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, uuid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAtomTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNodeNameBytes());
      }
      {
        int dataSize = 0;
        dataSize = 8 * getHandleSeqList().size();
        size += dataSize;
        size += 1 * getHandleSeqList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.opencog.atomspace.AtomSpaceProtos.AtomResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.opencog.atomspace.AtomSpaceProtos.AtomResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code atomspace.AtomResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.opencog.atomspace.AtomSpaceProtos.AtomResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencog.atomspace.AtomSpaceProtos.AtomResult.class, org.opencog.atomspace.AtomSpaceProtos.AtomResult.Builder.class);
      }

      // Construct using org.opencog.atomspace.AtomSpaceProtos.AtomResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind.NOT_FOUND;
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        atomType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nodeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        handleSeq_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencog.atomspace.AtomSpaceProtos.internal_static_atomspace_AtomResult_descriptor;
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomResult getDefaultInstanceForType() {
        return org.opencog.atomspace.AtomSpaceProtos.AtomResult.getDefaultInstance();
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomResult build() {
        org.opencog.atomspace.AtomSpaceProtos.AtomResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.opencog.atomspace.AtomSpaceProtos.AtomResult buildPartial() {
        org.opencog.atomspace.AtomSpaceProtos.AtomResult result = new org.opencog.atomspace.AtomSpaceProtos.AtomResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.atomType_ = atomType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nodeName_ = nodeName_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          handleSeq_ = java.util.Collections.unmodifiableList(handleSeq_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.handleSeq_ = handleSeq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencog.atomspace.AtomSpaceProtos.AtomResult) {
          return mergeFrom((org.opencog.atomspace.AtomSpaceProtos.AtomResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencog.atomspace.AtomSpaceProtos.AtomResult other) {
        if (other == org.opencog.atomspace.AtomSpaceProtos.AtomResult.getDefaultInstance()) return this;
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasAtomType()) {
          bitField0_ |= 0x00000004;
          atomType_ = other.atomType_;
          onChanged();
        }
        if (other.hasNodeName()) {
          bitField0_ |= 0x00000008;
          nodeName_ = other.nodeName_;
          onChanged();
        }
        if (!other.handleSeq_.isEmpty()) {
          if (handleSeq_.isEmpty()) {
            handleSeq_ = other.handleSeq_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureHandleSeqIsMutable();
            handleSeq_.addAll(other.handleSeq_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKind()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencog.atomspace.AtomSpaceProtos.AtomResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencog.atomspace.AtomSpaceProtos.AtomResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .atomspace.AtomResult.ResultKind kind = 1;
      private org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind.NOT_FOUND;
      /**
       * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
       */
      public org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind getKind() {
        return kind_;
      }
      /**
       * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
       */
      public Builder setKind(org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .atomspace.AtomResult.ResultKind kind = 1;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000001);
        kind_ = org.opencog.atomspace.AtomSpaceProtos.AtomResult.ResultKind.NOT_FOUND;
        onChanged();
        return this;
      }

      // optional fixed64 uuid = 2;
      private long uuid_ ;
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public long getUuid() {
        return uuid_;
      }
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public Builder setUuid(long value) {
        bitField0_ |= 0x00000002;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 uuid = 2;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uuid_ = 0L;
        onChanged();
        return this;
      }

      // optional string atom_type = 3;
      private java.lang.Object atomType_ = "";
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public boolean hasAtomType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public java.lang.String getAtomType() {
        java.lang.Object ref = atomType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          atomType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAtomTypeBytes() {
        java.lang.Object ref = atomType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          atomType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public Builder setAtomType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        atomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public Builder clearAtomType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        atomType_ = getDefaultInstance().getAtomType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string atom_type = 3;</code>
       */
      public Builder setAtomTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        atomType_ = value;
        onChanged();
        return this;
      }

      // optional string node_name = 4;
      private java.lang.Object nodeName_ = "";
      /**
       * <code>optional string node_name = 4;</code>
       */
      public boolean hasNodeName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public java.lang.String getNodeName() {
        java.lang.Object ref = nodeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nodeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNodeNameBytes() {
        java.lang.Object ref = nodeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public Builder setNodeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nodeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public Builder clearNodeName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nodeName_ = getDefaultInstance().getNodeName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_name = 4;</code>
       */
      public Builder setNodeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nodeName_ = value;
        onChanged();
        return this;
      }

      // repeated fixed64 handle_seq = 5;
      private java.util.List<java.lang.Long> handleSeq_ = java.util.Collections.emptyList();
      private void ensureHandleSeqIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          handleSeq_ = new java.util.ArrayList<java.lang.Long>(handleSeq_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getHandleSeqList() {
        return java.util.Collections.unmodifiableList(handleSeq_);
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public int getHandleSeqCount() {
        return handleSeq_.size();
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public long getHandleSeq(int index) {
        return handleSeq_.get(index);
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder setHandleSeq(
          int index, long value) {
        ensureHandleSeqIsMutable();
        handleSeq_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder addHandleSeq(long value) {
        ensureHandleSeqIsMutable();
        handleSeq_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder addAllHandleSeq(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureHandleSeqIsMutable();
        super.addAll(values, handleSeq_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated fixed64 handle_seq = 5;</code>
       */
      public Builder clearHandleSeq() {
        handleSeq_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:atomspace.AtomResult)
    }

    static {
      defaultInstance = new AtomResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:atomspace.AtomResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_atomspace_AtomRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_atomspace_AtomRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_atomspace_AtomsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_atomspace_AtomsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_atomspace_AtomResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_atomspace_AtomResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017atomspace.proto\022\tatomspace\"\274\001\n\013AtomReq" +
      "uest\0224\n\004kind\030\001 \002(\0162&.atomspace.AtomReque" +
      "st.AtomRequestKind\022\014\n\004uuid\030\002 \001(\006\022\021\n\tatom" +
      "_type\030\003 \001(\t\022\021\n\tnode_name\030\004 \001(\t\022\022\n\nhandle" +
      "_seq\030\005 \003(\006\"/\n\017AtomRequestKind\022\010\n\004UUID\020\000\022" +
      "\010\n\004NODE\020\001\022\010\n\004LINK\020\002\"8\n\014AtomsRequest\022(\n\010r" +
      "equests\030\001 \003(\0132\026.atomspace.AtomRequest\"\265\001" +
      "\n\nAtomResult\022.\n\004kind\030\001 \002(\0162 .atomspace.A" +
      "tomResult.ResultKind\022\014\n\004uuid\030\002 \001(\006\022\021\n\tat" +
      "om_type\030\003 \001(\t\022\021\n\tnode_name\030\004 \001(\t\022\022\n\nhand",
      "le_seq\030\005 \003(\006\"/\n\nResultKind\022\r\n\tNOT_FOUND\020" +
      "\000\022\010\n\004NODE\020\001\022\010\n\004LINK\020\002B(\n\025org.opencog.ato" +
      "mspaceB\017AtomSpaceProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_atomspace_AtomRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_atomspace_AtomRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_atomspace_AtomRequest_descriptor,
              new java.lang.String[] { "Kind", "Uuid", "AtomType", "NodeName", "HandleSeq", });
          internal_static_atomspace_AtomsRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_atomspace_AtomsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_atomspace_AtomsRequest_descriptor,
              new java.lang.String[] { "Requests", });
          internal_static_atomspace_AtomResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_atomspace_AtomResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_atomspace_AtomResult_descriptor,
              new java.lang.String[] { "Kind", "Uuid", "AtomType", "NodeName", "HandleSeq", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
